export const DOMAIN = process.env.REACT_APP_API_PROTOCAL + '://' + window.location.hostname + ':' + process.env.REACT_APP_BACKEND_PORT
export const LOGIN = '/account/login'
export const ACCOUNT_UPDATE = '/account/update?account_id='
export const ABOUT_ME = '/account/me'
export const ACCOUNTS = '/account/get-all'
export const ACCOUNTS_AVAILABLE = '/account/get-all-active'
export const STAFF_UPDATE = '/account/update-staff?account_id='
export const ACCOUNT_DISABLE = '/account/disable?account_id='
export const ACCOUNT_UNDISABLED = '/account/undisabled?account_id='
export const ACCOUNT_CREATE = '/account/register'